services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    command: ["redis-server", "--requfdirepass", "${REDIS_PASSWORD}"]
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: go_app
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
